apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: log
  name: log
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: log
    spec:
      containers:
      - args:
        - rabbitmqalias
        image: sreesanpd/helloworldmicroservices_log
        name: log
        resources: {}
      restartPolicy: Always
status: {}
